// The catalogue is authored: every vertical has twenty named, buildable props.
// Families share a voxel construction language; variants alter silhouette/details.
const rows = [
['software','Software studio','💻','#a894d2','Code terminal:terminal|Build server:server|Debug rubber duck:duck|Mechanical keyboard:keyboard|Pixel plant:plant|Sprint board:board|API gateway:antenna|Release rocket:rocket|Bug jar:jar|Reference bookshelf:books|Pairing station:computer|Test trophy:trophy|Coffee machine:coffee|Repository vault:vault|Feature phone:phone|Design tablet:tablet|Headphone stand:headphones|Night lamp:lamp|Documentation stack:book|Shipping crate:crate'],
['ai','AI & machine learning','🧠','#86b3ce','GPU tower:server|Neural core:brain|Training terminal:terminal|Robot assistant:robot|Dataset library:books|Vision camera:camera|Tensor blocks:blocks|Inference chip:chip|Model trophy:trophy|Compute battery:battery|Research whiteboard:board|Voice microphone:microphone|Language books:book|Edge device:phone|Sensor array:antenna|Experiment flask:flask|Safety shield:shield|Benchmark chart:chart|Data cartridge:cartridge|Model capsule:capsule'],
['security','Cybersecurity','🛡️','#658ea8','Security vault:vault|Network shield:shield|Encryption lock:lock|Firewall tower:server|Audit terminal:terminal|Surveillance camera:camera|Access card:card|Key cabinet:cabinet|Signal jammer:antenna|Evidence case:suitcase|Incident board:board|Backup cartridge:cartridge|Secure phone:phone|Hardware token:chip|Alert beacon:beacon|Packet router:router|Fingerprint scanner:scanner|Bug detector:radio|Red team trophy:trophy|Forensics microscope:microscope'],
['finance','Finance & banking','💰','#7fad95','Bank vault:vault|Gold bullion:gold|Coin stack:coins|Trading terminal:terminal|Market chart:chart|Bank counter:counter|ATM kiosk:atm|Ledger book:book|Calculator:calculator|Receipt printer:printer|Credit card:card|Document cabinet:cabinet|Desk telephone:phone|Closing bell:bell|Briefcase:suitcase|Balance scales:scales|Price ticker:sign|Currency sorter:register|Investment trophy:trophy|Security camera:camera'],
['crypto','Web3 & digital assets','🔗','#b69ace','Mining rig:server|Cold wallet:cartridge|Token sculpture:coins|Chain monument:chain|Validation node:router|Ledger terminal:terminal|Hardware wallet:phone|Smart contract:book|Network globe:globe|Key vault:vault|Crypto chip:chip|Block stack:blocks|Protocol antenna:antenna|Audit shield:shield|Exchange kiosk:atm|Gas battery:battery|Wallet lock:lock|Governance board:board|Node beacon:beacon|Genesis trophy:trophy'],
['commerce','Commerce & retail','🛍️','#df9d93','Shop counter:counter|Checkout till:register|Shopping cart:cart|Parcel stack:parcel|Product shelf:shelf|Barcode scanner:scanner|Delivery van:truck|Receipt printer:printer|Gift box:gift|Clothing rack:rack|Price sign:sign|Stock crate:crate|Storefront:shop|Payment terminal:phone|Shopping bag:bag|Returns cabinet:cabinet|Display mannequin:mannequin|Sale balloon:balloon|Stock tablet:tablet|Store plant:plant'],
['health','Healthcare','🩺','#88bcb8','Patient bed:bed|Heart monitor:monitor|Medicine cabinet:cabinet|Pill bottle:pills|First aid kit:medkit|Microscope:microscope|X-ray viewer:xray|DNA model:dna|Wheelchair:wheelchair|Lab scanner:scanner|Health tablet:tablet|IV stand:iv|Sample tray:vials|Anatomical heart:heart|Sanitizer pump:pump|Appointment desk:counter|Stethoscope:stethoscope|Care plant:plant|Ambulance:truck|Medical chart:chart'],
['biotech','Biotech & genetics','🧬','#a4b880','DNA helix:dna|Cell incubator:cabinet|Centrifuge:centrifuge|Sample microscope:microscope|Culture flask:flask|Specimen jar:jar|Sample vials:vials|Pipette rack:rack|Gene sequencer:server|Lab terminal:terminal|Cryogenic capsule:capsule|Research board:board|Biohazard bin:bin|Petri stack:plates|Protein sculpture:molecule|Cold storage:fridge|Lab scanner:scanner|Sterile cabinet:shelf|Cell model:orb|Research books:books'],
['education','Education & learning','📚','#dbb86e','Classroom board:board|Library shelf:books|Open textbook:book|School globe:globe|Abacus:abacus|Pencil cup:pencils|School bell:bell|Learning tablet:tablet|Graduation cap:cap|Student trophy:trophy|Counting blocks:blocks|Classroom microscope:microscope|School backpack:bag|Art easel:easel|Science rocket:rocket|Reading lamp:lamp|Lesson projector:projector|Music keyboard:keyboard|Geometric solids:shapes|Class plant:plant'],
['games','Games & interactive','🎮','#b497d8','Arcade cabinet:arcade|Game controller:controller|Retro console:console|Pixel sword:sword|Quest chest:chest|Giant dice:dice|Victory trophy:trophy|Racing wheel:wheel|Pixel ghost:ghost|Level blocks:blocks|Gaming monitor:monitor|VR headset:headset|Board game:chess|Pinball machine:pinball|Health potion:flask|Game cartridge:cartridge|Collectible robot:robot|Pixel heart:heart|Streamer microphone:microphone|Prize claw:claw'],
['music','Music & audio','🎵','#d4a180','Grand piano:piano|Electric guitar:guitar|Drum kit:drums|Studio microphone:microphone|Monitor speaker:speaker|Synth keyboard:keyboard|Vinyl turntable:turntable|Record crate:crate|Audio mixer:mixer|Headphone stand:headphones|Saxophone:sax|Music score:book|Amplifier:amp|Tape deck:radio|Concert trophy:trophy|Acoustic panels:panel|Stage light:spotlight|Music stand:rack|Festival poster:sign|Bass guitar:guitar'],
['film','Film & animation','🎬','#859ba9','Cinema camera:camera|Director chair:chair|Clapperboard:clapper|Film projector:projector|Spotlight rig:spotlight|Film reel:reel|Editing terminal:terminal|Boom microphone:microphone|Storyboard:board|Prop chest:chest|Cinema sign:sign|Award statue:trophy|Makeup mirror:mirror|Red carpet:carpet|Green screen:panel|Studio speaker:speaker|Animation lightbox:tablet|Costume rack:rack|Camera drone:drone|Popcorn cart:cart'],
['architecture','Architecture','📐','#c5aa88','Scale house:house|Drafting table:table|Blueprint roll:scroll|Drawing board:board|Building model:tower|Material samples:blocks|Architect lamp:lamp|Model tree:tree|Concrete arch:arch|Facade panel:panel|Site crane:crane|CAD terminal:terminal|Survey tripod:tripod|Portfolio book:book|City blocks:city|Measuring ruler:ruler|Design award:trophy|Brick palette:crate|Pencil holder:pencils|Studio plant:plant'],
['construction','Construction','🏗️','#d6ac65','Tower crane:crane|Cement mixer:mixer|Safety cone:cone|Tool cabinet:cabinet|Brick stack:blocks|Pallet jack:forklift|Scaffold:rack|Hard hat:helmet|Site blueprint:scroll|Work bench:table|Power drill:drill|Concrete barrier:barrier|Dump truck:truck|Site radio:radio|Steel beam:beam|Tool box:toolbox|Warning beacon:beacon|Survey tripod:tripod|Water pump:pump|Site office:house'],
['robotics','Robotics','🤖','#91aaa8','Robot arm:robotarm|Friendly robot:robot|Assembly conveyor:conveyor|Sensor array:antenna|Robot rover:rover|Control terminal:terminal|Servo motor:motor|Circuit board:chip|Charging dock:battery|Safety cage:rack|Vision camera:camera|Gripper rig:robotarm|Parts cabinet:cabinet|Prototype drone:drone|Calibration board:board|Tool station:toolbox|Diagnostic tablet:tablet|Actuator stack:blocks|Test beacon:beacon|Robot trophy:trophy'],
['aerospace','Aerospace','🚀','#a4acc5','Launch rocket:rocket|Satellite:satellite|Lunar rover:rover|Mission terminal:terminal|Astronaut helmet:helmet|Rocket engine:motor|Control antenna:antenna|Wind tunnel:tube|Fuel tank:tank|Flight simulator:console|Launch tower:tower|Cargo capsule:capsule|Solar array:solar|Orbit model:planet|Airplane model:plane|Test chamber:cabinet|Telemetry dish:dish|Mission patch:shield|Countdown board:sign|Landing pad:pad'],
['astronomy','Astronomy & space','🔭','#aaa1c9','Observatory telescope:telescope|Ringed planet:planet|Star globe:globe|Radio telescope:dish|Meteor specimen:rock|Orbit mobile:satellite|Moon lander:rover|Star chart:board|Observatory dome:dome|Deep space probe:rocket|Cosmic library:books|Solar system:orbits|Tracking terminal:terminal|Spectrometer:scanner|Comet sculpture:comet|Astronomy camera:camera|Astrolabe:wheel|Starlight lamp:lamp|Lunar sample:jar|Mission plaque:sign'],
['automotive','Automotive & mobility','🚗','#c79582','Electric car:car|Charging station:charger|Tire stack:tires|Engine stand:motor|Workshop lift:rack|Tool chest:toolbox|Steering wheel:wheel|Diagnostic console:terminal|Traffic signal:traffic|Model bus:bus|Battery pack:battery|Paint booth:cabinet|Safety helmet:helmet|Inspection lamp:lamp|Parts shelf:shelf|Fuel pump:pump|Road barrier:barrier|Race trophy:trophy|Delivery scooter:scooter|Road sign:sign'],
['logistics','Logistics & supply chain','📦','#c8aa7b','Delivery truck:truck|Forklift:forklift|Pallet crates:crate|Parcel conveyor:conveyor|Storage rack:rack|Shipping container:container|Barcode scanner:scanner|Route board:board|Loading trolley:cart|Warehouse beacon:beacon|Dispatch terminal:terminal|Delivery drone:drone|Weighing scale:scales|Packing bench:table|Label printer:printer|Mail sack:bag|Cargo ship:ship|Freight train:train|Route globe:globe|Packing rolls:rolls'],
['travel','Travel & tourism','🧳','#87b4c2','Travel suitcase:suitcase|World globe:globe|Airplane model:plane|Departure board:sign|Passport:book|Luggage trolley:cart|Camera:camera|Beach umbrella:umbrella|Travel poster:panel|Ticket kiosk:atm|Compass:compass|Hot air balloon:balloon|Camp tent:tent|Mountain model:mountain|Train model:train|Cruise ship:ship|Road trip van:bus|Travel backpack:bag|Souvenir shelf:shelf|Palm tree:palm'],
['hospitality','Hotels & hospitality','🛎️','#c8a192','Reception bell:bell|Concierge desk:counter|Luggage cart:cart|Hotel bed:bed|Room key:card|Lobby sofa:sofa|Bedside lamp:lamp|Hotel plant:plant|Mini fridge:fridge|Breakfast tray:plates|Bath towel stack:rolls|Suitcase:suitcase|Room sign:sign|Coffee maker:coffee|Service telephone:phone|Flower vase:flowers|Pool chair:chair|Cocktail glass:glass|Welcome gift:gift|Grand piano:piano'],
['food','Food & restaurants','🍜','#d4a27d','Pizza oven:oven|Chef counter:counter|Coffee machine:coffee|Burger stack:burger|Sushi board:sushi|Birthday cake:cake|Stand mixer:mixer|Recipe book:book|Frying pan:pan|Stock pot:pot|Kitchen fridge:fridge|Bread basket:bread|Vegetable crate:crate|Espresso cup:mug|Dining table:table|Menu board:board|Food truck:truck|Knife block:knives|Noodle bowl:bowl|Herb planter:plant'],
['agriculture','Agriculture','🌾','#a9b778','Farm tractor:tractor|Grain silo:silo|Wheat bundle:wheat|Vegetable box:crate|Greenhouse:greenhouse|Watering can:watering|Bee hive:hive|Irrigation pump:pump|Orchard tree:tree|Farm drone:drone|Soil sensor:antenna|Seed bag:bag|Barn:house|Harvest cart:cart|Corn stalk:corn|Weather station:weather|Farm terminal:terminal|Seedling tray:planter|Sunflower:flowers|Compost bin:bin'],
['climate','Climate & environment','🌍','#8eaf87','Earth globe:globe|Wind turbine:wind|Solar panel:solar|Recycling station:bin|Carbon tree:tree|Air quality sensor:weather|Rain barrel:tank|Research boat:ship|Coral sample:coral|Climate chart:chart|Mountain model:mountain|Water testing kit:vials|Leaf sculpture:leaf|Electric charger:charger|Eco shelter:house|Compost planter:planter|Weather satellite:satellite|Field backpack:bag|Research board:board|Clean water pump:pump'],
['energy','Energy & utilities','⚡','#c5b55c','Wind turbine:wind|Solar array:solar|Battery tower:battery|Power transformer:transformer|Grid pylon:pylon|Hydro wheel:wheel|Generator:motor|Control panel:console|Charging pedestal:charger|Utility meter:meter|Fuel cell:cell|Energy globe:globe|Grid board:board|Power cable reel:reel|Safety helmet:helmet|Service truck:truck|Substation:server|Warning beacon:beacon|Cooling tower:tower|Smart thermostat:thermostat'],
['ocean','Ocean & marine','🌊','#7aaebc','Research aquarium:aquarium|Coral reef:coral|Submarine:submarine|Research ship:ship|Sonar dish:dish|Diving helmet:helmet|Ocean buoy:buoy|Tide sensor:antenna|Fish specimen:fish|Nautical compass:compass|Anchor:anchor|Shell display:shell|Lighthouse:tower|Marine globe:globe|Wave model:wave|Sampling vials:vials|Seaweed planter:plant|Ocean chart:board|Underwater drone:rover|Dock bollard:post'],
['sports','Sports','🏆','#baac70','Football:football|Basketball hoop:hoop|Victory cup:trophy|Scoreboard:sign|Tennis racket:racket|Baseball bat:bat|Sports locker:cabinet|Race podium:podium|Team jersey:shirt|Running shoe:shoe|Table tennis:pingpong|Whistle:whistle|Water cooler:cooler|Stadium model:stadium|Sports bag:bag|Goal post:goal|Medal rack:medal|Team bench:bench|Training cones:cone|Race bicycle:bike'],
['fitness','Fitness & wellness','🏋️','#aaa888','Dumbbell rack:dumbbell|Treadmill:treadmill|Yoga mat:carpet|Exercise bike:bike|Kettlebell:kettlebell|Water bottle:bottle|Balance ball:orb|Gym locker:cabinet|Weight bench:bench|Resistance bands:chain|Wellness plant:plant|Protein blender:blender|Meditation cushion:cushion|Punching bag:punchbag|Gym timer:clock|Fitness tablet:tablet|Recovery bed:bed|Foam roller:rolls|Workout chart:board|Finish medal:medal'],
['fashion','Fashion & apparel','🧵','#d19caa','Sewing machine:sewing|Dress mannequin:mannequin|Clothing rack:rack|Fabric rolls:rolls|Thread spools:spools|Scissors:scissors|Designer shoe:shoe|Pattern table:table|Full length mirror:mirror|Handbag:bag|Fashion books:books|Steam iron:iron|Button jar:jar|Tailor tape:ruler|Style moodboard:board|Display plinth:podium|Fashion camera:camera|Jewelry bust:bust|Sketch tablet:tablet|Hat stand:hat'],
['beauty','Beauty & cosmetics','💄','#dca6b2','Lipstick:lipstick|Perfume bottle:perfume|Makeup mirror:mirror|Brush cup:brushes|Nail polish:polish|Skincare jar:jar|Salon chair:chair|Hair dryer:dryer|Product shelf:shelf|Color palette:palette|Spa towel:rolls|Aroma diffuser:diffuser|Beauty ring light:ringlight|Flower vase:flowers|Serum dropper:dropper|Compact case:compact|Manicure station:table|Makeup bag:bag|Cosmetic cabinet:cabinet|Brand display:sign'],
['property','Real estate','🏠','#b1ba91','Model home:house|Apartment tower:tower|Property keys:key|Sold sign:sign|Floorplan board:board|Welcome mat:carpet|Lounge sofa:sofa|Sample kitchen:counter|Model garden:planter|For sale brochure:book|Agent briefcase:suitcase|Smart lock:lock|Video doorbell:camera|Mortgage calculator:calculator|City model:city|Interior lamp:lamp|Property globe:globe|Contract folder:card|Viewing tablet:tablet|Office flowers:flowers'],
['legal','Legal & compliance','⚖️','#b5a08c','Justice scales:scales|Law library:books|Gavel:gavel|Legal briefcase:suitcase|Contract book:book|Document vault:vault|Court podium:podium|Evidence case:chest|Filing cabinet:cabinet|Desk lamp:lamp|Legal seal:stamp|Office telephone:phone|Reference globe:globe|Case board:board|Privacy shield:shield|Court clock:clock|Document scanner:scanner|Client chair:chair|Ink pen:pencils|Office bonsai:tree'],
['marketing','Marketing & advertising','📣','#d7a977','Campaign billboard:sign|Megaphone:megaphone|Moodboard:board|Analytics terminal:terminal|Brand trophy:trophy|Product plinth:podium|Studio camera:camera|Social phone:phone|Campaign chart:chart|Swatch fan:palette|Strategy book:book|Podcast microphone:microphone|Display kiosk:atm|Gift bag:bag|Ad projector:projector|Launch balloon:balloon|Creative tablet:tablet|Sample packaging:gift|Brand sculpture:shapes|Idea lamp:lamp'],
['social','Social & community','💬','#ac9cce','Community board:board|Chat bubble:chat|Creator camera:camera|Podcast mic:microphone|Social phone:phone|Reaction heart:heart|Livestream ring:ringlight|Community sofa:sofa|Discussion table:table|Welcome banner:sign|Community trophy:trophy|Event balloon:balloon|Donation box:chest|Message mailbox:mailbox|Member badges:medal|Sticker printer:printer|Photo booth:booth|Creator tablet:tablet|Meetup plant:plant|Gift parcel:gift'],
['news','News & journalism','📰','#a4b4b8','Press camera:camera|News microphone:microphone|Typewriter:typewriter|Newspaper stack:book|Broadcast desk:counter|Press badge:card|Field recorder:radio|World globe:globe|Newsroom clock:clock|Satellite uplink:dish|Research board:board|Editorial terminal:terminal|News van:truck|Story archive:cabinet|Teleprompter:monitor|Studio light:spotlight|Headline sign:sign|Reporter bag:bag|Press award:trophy|Coffee mug:mug'],
['photography','Photography','📷','#b1a294','Studio camera:camera|Camera tripod:tripod|Softbox:spotlight|Lens case:suitcase|Film reel:reel|Light meter:meter|Editing tablet:tablet|Backdrop stand:panel|Print enlarger:projector|Photo printer:printer|Lens rack:shelf|Camera drone:drone|Portrait bust:bust|Reflector disc:ringlight|Photo frames:frame|Gallery plinth:podium|Negative archive:cabinet|Camera bag:bag|Memory card:cartridge|Photo books:books'],
['publishing','Books & publishing','📖','#c5a286','Library shelf:books|Open manuscript:book|Printing press:printer|Typewriter:typewriter|Book cart:cart|Reading lamp:lamp|Editorial board:board|Ink bottle:jar|Paper rolls:rolls|Book parcel:parcel|Publisher stamp:stamp|Author bust:bust|Reading armchair:chair|E-reader:tablet|Poetry microphone:microphone|Bookmark stand:rack|Edition trophy:trophy|Reference globe:globe|Binding machine:sewing|Bookshop sign:sign'],
['geospatial','Maps & geospatial','🗺️','#9cb69d','Terrain model:mountain|Survey drone:drone|World globe:globe|Satellite:satellite|GPS receiver:phone|Survey tripod:tripod|Compass:compass|Map table:table|Topography board:board|Field backpack:bag|Geological sample:rock|Lidar scanner:scanner|Navigation beacon:beacon|Weather sensor:weather|Route terminal:terminal|City model:city|Ocean chart:book|Survey rover:rover|Mapping antenna:antenna|Map scroll:scroll'],
['telecom','Telecommunications','📡','#8aaab5','Radio tower:antenna|Satellite dish:dish|Fiber router:router|Network rack:server|Desk phone:phone|Fiber reel:reel|Signal meter:meter|Telecom satellite:satellite|Cable cabinet:cabinet|Network console:console|Mobile mast:pylon|Walkie talkie:radio|Patch panel:panel|Switch chip:chip|Coverage globe:globe|Field case:suitcase|Modem:router|Network chart:board|Service van:truck|Connection beacon:beacon'],
['iot','IoT & smart home','🏡','#9bb9bc','Smart thermostat:thermostat|Home hub:router|Smart speaker:speaker|Door camera:camera|Sensor board:chip|Smart lock:lock|Connected bulb:lamp|Weather station:weather|Smart plug:plug|Home model:house|Energy meter:meter|Robot vacuum:vacuum|Garden sensor:plant|Control tablet:tablet|Smart fridge:fridge|IoT antenna:antenna|Automation board:board|Charging station:charger|Connected watch:watch|Garage controller:console'],
['manufacturing','Manufacturing','🏭','#a9aaa0','Assembly arm:robotarm|Factory conveyor:conveyor|CNC machine:cnc|Parts bin:bin|Control terminal:terminal|Industrial lathe:lathe|Work station:table|Quality scanner:scanner|Safety helmet:helmet|Forklift:forklift|Tool cabinet:toolbox|Factory model:factory|Materials pallet:crate|Pressure gauge:meter|Factory beacon:beacon|3D printer:printer3d|Inspection scope:microscope|Gear display:gear|Storage tank:tank|Production board:board'],
['chemistry','Chemistry','⚗️','#b2b38b','Erlenmeyer flask:flask|Test tube rack:vials|Molecule model:molecule|Bunsen burner:burner|Safety goggles:headset|Fume cabinet:cabinet|Lab centrifuge:centrifuge|Periodic table:board|Chemical jar:jar|Beaker:glass|Lab scales:scales|Distillation tower:tube|Sample microscope:microscope|Stir plate:hotplate|Lab fridge:fridge|Dropper:dropper|Safety shower:pump|Chemical books:books|Storage drum:tank|Crystal model:crystal'],
['physics','Physics & research','⚛️','#93a8bc','Particle accelerator:ring|Optical bench:table|Laser emitter:laser|Newton cradle:cradle|Oscilloscope:monitor|Magnetic coil:coil|Vacuum chamber:dome|Physics books:books|Wave generator:console|Atom model:molecule|Prism:crystal|Pendulum:pendulum|Electric motor:motor|Lab power supply:battery|Circuit board:chip|Research board:board|Detector array:panel|Superconductor:tank|Lab terminal:terminal|Research medal:medal'],
['mathematics','Mathematics & data','📊','#a4a7c3','Equation board:board|Abacus:abacus|Geometry solids:shapes|Graph sculpture:chart|Calculator:calculator|Probability dice:dice|Math books:books|Infinity sculpture:ring|Data terminal:terminal|Counting blocks:blocks|Geometric compass:compass|Reference ruler:ruler|Mobius model:chain|Algorithm chess:chess|Fractal tree:tree|Data server:server|Statistics tablet:tablet|Logic puzzle:cube|Research trophy:trophy|Study lamp:lamp'],
['art','Art & design','🎨','#d9ac9b','Painting easel:easel|Color palette:palette|Brush jar:brushes|Sculpture bust:bust|Pottery wheel:wheel|Clay vase:vase|Design tablet:tablet|Swatch board:board|Gallery frame:frame|Studio stool:chair|Art books:books|Print rack:rack|Paint cans:jar|Sketch pencils:pencils|Sculpture pedestal:podium|Ceramic bowls:bowl|Creative lamp:lamp|Paper rolls:rolls|Art award:trophy|Studio flowers:flowers'],
['pets','Pets & animals','🐾','#c5ac84','Pet bed:cushion|Food bowl:bowl|Cat tree:cattree|Dog house:house|Aquarium:aquarium|Bird cage:cage|Pet carrier:crate|Chew toy:bone|Treat jar:jar|Grooming table:table|Animal care kit:medkit|Pet portrait:frame|Leash hook:rack|Cat scratcher:post|Water fountain:pump|Tennis ball:orb|Adoption board:board|Pet scale:scales|Food bag:bag|Training trophy:trophy'],
['gardening','Gardens & plants','🪴','#91b183','Greenhouse:greenhouse|Potting bench:table|Watering can:watering|Bonsai tree:tree|Flower planter:flowers|Seedling tray:planter|Garden trowel:shovel|Compost bin:bin|Terrarium:terrarium|Cactus:cactus|Seed packets:card|Garden wheelbarrow:cart|Rain barrel:tank|Garden statue:bust|Bird bath:fountain|Climbing trellis:rack|Garden boots:shoe|Flower arch:arch|Plant books:books|Garden lantern:lamp'],
['events','Events & entertainment','🎉','#c8a0c4','Balloon cluster:balloon|DJ turntable:turntable|Stage speaker:speaker|Spotlight:spotlight|Ticket booth:booth|Confetti cannon:cannon|Festival tent:tent|Photo booth:camera|Stage microphone:microphone|Welcome arch:arch|Gift table:table|Event banner:sign|Party cake:cake|Dance floor:carpet|Wristband rack:rack|Event cooler:cooler|Award cup:trophy|Seating bench:bench|Catering cart:cart|Flower arrangement:flowers'],
['civic','Civic & public services','🏛️','#aaa889','City hall:modelhall|Public mailbox:mailbox|Street lamp:lamp|Transit bus:bus|City map:board|Park bench:bench|Public fountain:fountain|Recycling bin:bin|Traffic light:traffic|Service kiosk:atm|Council podium:podium|City tree:tree|Library books:books|Emergency kit:medkit|Public clock:clock|Service truck:truck|Town model:city|Bike rack:bike|Water tower:silo|Civic banner:sign'],
['productivity','Productivity & collaboration','✅','#a7b995','Task board:board|Focus timer:clock|Calendar:calendar|Notebook:book|Standing desk:table|Desk lamp:lamp|Coffee mug:mug|Meeting monitor:monitor|Reference shelf:books|Pencil cup:pencils|Document tray:printer|Team trophy:trophy|Focus headphones:headphones|Desk plant:plant|Planner tablet:tablet|Inbox mailbox:mailbox|Filing cabinet:cabinet|Idea bulb:lamp|Team sofa:sofa|Celebration bell:bell'],
];

export const verticals = rows.map(([id,name,icon,color,entries]) => ({ id,name,icon,color, props:entries.split('|').map((entry,i)=>{const [name,baseFamily]=entry.split(':');const family=name==='Stand mixer'?'standmixer':name==='Cement mixer'?'cementmixer':baseFamily;return {id:`${id}-${String(i+1).padStart(2,'0')}`,name,family,variant:i%4,color,vertical:id};}) }));
export const allProps = verticals.flatMap(v=>v.props);
export const verticalById = new Map(verticals.map(v=>[v.id,v]));
export const propById = new Map(allProps.map(p=>[p.id,p]));
export function suggestedVertical(name, fallback='software') {
  const text=name.toLowerCase();
  const rules=[[/\b(ai|llm|neural|model)\b/,'ai'],[/\b(game|gaming|pixel)\b/,'games'],[/\b(health|medical|clinic)\b/,'health'],[/\b(space|orbit|rocket)\b/,'aerospace'],[/\b(kitchen|food|recipe)\b/,'food'],[/\b(bloom|garden|plant)\b/,'gardening'],[/\b(bank|finance|trading)\b/,'finance'],[/\b(music|audio|sound)\b/,'music'],[/\b(shop|store|commerce)\b/,'commerce'],[/\b(security|auth|cyber)\b/,'security']];
  return String(rules.find(([rule])=>rule.test(text))?.[1]??fallback);
}
