import { Component, lazy, Suspense, useEffect, useMemo, useState, type ReactNode } from 'react';
import { Activity, ArrowUpRight, ChevronRight, Coffee, Cookie, Crosshair, Hand, Heart, Home, Leaf, Maximize2, Minus, Moon, Pause, Play, Plus, Plug, RotateCw, Search, Settings2, Sun, Users, X } from 'lucide-react';
import { effectiveState, projectsOf, stateMeta, sessionsOf, summarizeAgents, teamMeta, type Agent, type Project } from '../shared/protocol';
import { officePlan } from '../shared/layout';
import TeamHierarchy from './TeamHierarchy';
import { useOffice } from './useOffice';
import ConnectDialog from './ConnectDialog';
import type { CameraAction, Designs, RoomDesign } from './scene/OfficeScene';
import type { Reaction } from './scene/Character';
import type { WorldAction } from './scene/WorldProps';
import { playFeedback } from './sound';
import { loadDesigns } from './designs';
import { verticalById, suggestedVertical } from '../shared/verticals.mjs';
const PropLibrary = lazy(() => import('./PropLibrary'));
const OfficeScene = lazy(() => import('./scene/OfficeScene'));
const colors = { studio: '#aa88e0', lab: '#63b69c', garden: '#e3bf60' };
function elapsed(at: number, now: number) { const s = Math.max(0, Math.floor((now - at) / 1000)); return s < 60 ? 'now' : s < 3600 ? `${Math.floor(s / 60)}m` : `${Math.floor(s / 3600)}h`; }
function Minimap({ projects, designs, focus, selected, onFocus }: { designs: Designs; projects: Project[]; focus: string | null; selected: string; onFocus: (id: string) => void }) {
  const plan=officePlan(projects),b=plan.bounds;
  return <svg viewBox={`${b.x-b.w/2-1} ${b.z-b.d/2-1} ${b.w+2} ${b.d+2}`} aria-label="Office minimap">
    {[plan.hall,plan.reception,plan.lounge,plan.meeting,...(plan.quiet?[plan.quiet]:[])].map((r,i)=><rect key={i} x={r.x-r.w/2} y={r.z-r.d/2} width={r.w} height={r.d} fill={i<2?'#d6cfb7':'#91a49b'} rx=".3"/>)}
    {plan.rooms.map(r=><g key={r.id} role="button" aria-label={`Focus ${r.name} · ${r.session.name}`} tabIndex={0} onClick={()=>onFocus(r.projectId)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onFocus(r.projectId)}}} className="map-room"><rect x={r.x-r.w/2} y={r.z-r.d/2} width={r.w} height={r.d} rx=".3" fill={verticalById.get(designs[r.projectId]?.vertical??suggestedVertical(r.name))?.color??colors[r.theme]} opacity={focus===r.projectId?1:.7}/>{r.seats.map(seat=><circle key={seat.agent.key} cx={seat.x} cy={seat.z} r=".55" fill={seat.agent.key===selected?'#fff7d9':'#47665f'}/>)}</g>)}
  </svg>;
}
class SceneBoundary extends Component<{ children: ReactNode }, { failed: boolean }> {
  state = { failed: false }; static getDerivedStateFromError() { return { failed: true }; }
  render() { return this.state.failed ? <div className="canvas-fallback">The 3D world couldn’t start. Try a WebGL-capable browser.</div> : this.props.children; }
}
export default function App() {
  const { office, mode, connection, paused, setPaused, now, enterLive, enterDemo, forgetOffice, officeId } = useOffice();
  const [panel, setPanel] = useState<'team' | 'activity' | 'settings' | null>(null);
  const [selectedKey, setSelectedKey] = useState('');
  const [focus, setFocus] = useState<string | null>(null), [follow, setFollow] = useState<string | null>(null);
  const [reaction, setReaction] = useState<Reaction>(), [cameraAction, setCameraAction] = useState<CameraAction>();
  const [evening, setEvening] = useState(false), [speed, setSpeed] = useState(1);
  const [reducedMotion, setReducedMotion] = useState(() => matchMedia('(prefers-reduced-motion: reduce)').matches);
  const [connectOpen, setConnectOpen] = useState(false), [query, setQuery] = useState('');
  const [libraryOpen,setLibraryOpen] = useState(false);
  const [designs,setDesigns] = useState<Designs>(loadDesigns);
  const [sound,setSound] = useState(false);
  const [pulses,setPulses] = useState<Partial<Record<WorldAction,number>>>({});
  const [worldToast,setWorldToast] = useState<{text:string;at:number}>();
  function worldAction(kind:WorldAction) { setPulses(p=>({...p,[kind]:Date.now()})); playFeedback(kind,sound); setWorldToast({text:kind==='coffee'?'☕ Fresh coffee. The best office perk.':kind==='arcade'?'👾 New high score! Back to work… eventually.':kind==='fountain'?'✨ A tiny wish for green tests.':'🎵 Good vibes delivered.',at:Date.now()}); }
  function designRoom(id:string,design:RoomDesign){setDesigns(current=>{const next={...current,[id]:design};localStorage.setItem('sidequest.designs',JSON.stringify(next));return next;});setFocus(id);setFollow(null);playFeedback('cheer',sound);}
  const projects = useMemo(() => projectsOf(office), [office]);
  const selected = office.agents.find(a => a.key === selectedKey);
  const working = office.agents.filter(a => ['coding', 'thinking', 'testing', 'reading'].includes(effectiveState(a, now))).length;
  const needsYou = office.agents.filter(a => ['waiting', 'blocked'].includes(effectiveState(a, now)));
  const selectedState = selected ? effectiveState(selected, now) : 'idle';
  const children = selected ? office.agents.filter(a => a.parentAgentId === selected.agentId && a.sessionId === selected.sessionId && a.provider === selected.provider) : [];
  const parent = selected?.parentAgentId ? office.agents.find(a => a.agentId === selected.parentAgentId && a.sessionId === selected.sessionId && a.provider === selected.provider) : undefined;
  function selectAgent(a: Agent) { setSelectedKey(a.key); setPanel(null); }
  function camera(type: CameraAction['type']) { setFollow(null); if (type === 'home') setFocus(null); setCameraAction({ type, id: Date.now() }); }
  function focusRoom(id: string | null) { setFollow(null); setFocus(id); if (!id) camera('home'); }
  function react(kind: Reaction['kind']) { if (selected) {setReaction({ key: selected.key, kind, at: Date.now() });playFeedback(kind,sound);} }
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if(libraryOpen){if(event.key==='Escape')setLibraryOpen(false);return;}
      if (['INPUT','TEXTAREA','SELECT'].includes((event.target as HTMLElement)?.tagName) || document.querySelector('dialog[open]')) return;
      if (event.code === 'Space') { event.preventDefault(); setPaused(p => !p); }
      if (event.key.toLowerCase() === 'f') { setFollow(null); setFocus(null); setCameraAction({ type: 'home', id: Date.now() }); }
      if (event.key === 'Escape') { setLibraryOpen(false); setSelectedKey(''); setFollow(null); setPanel(null); }
    };
    window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey);
  }, [setPaused,libraryOpen]);
  const status = <span className="agent-status" style={{ color: stateMeta[selectedState].color }}><i />{stateMeta[selectedState].label}</span>;
  return <main className={`game ${evening ? 'night' : ''}`}>
    <SceneBoundary><Suspense fallback={<div className="world-loading"><img src="/favicon.svg" alt=""/><span>Turning on the office lights…</span></div>}><OfficeScene projects={projects} selected={selectedKey} onSelect={selectAgent} reaction={reaction} now={now} paused={paused} reducedMotion={reducedMotion} focus={focus} action={cameraAction} evening={evening} speed={speed} follow={follow} designs={designs} onWorldAction={worldAction} pulses={pulses} /></Suspense></SceneBoundary>
    <div className="game-vignette" />
    <header className="game-header">
      <div className="world-brand"><img src="/favicon.svg" alt=""/><div><strong>SIDEQUEST</strong><small>{mode === 'demo' ? 'DEMO OFFICE' : 'YOUR LIVING OFFICE'}</small></div></div>
      <div className="office-stats glass"><span><Users size={15}/><b>{office.agents.length}</b> in office</span><span><i className="live-dot"/><b>{working}</b> working</span>{needsYou.length > 0 && <button className="help-alert" onClick={() => { selectAgent(needsYou[0]); setFollow(needsYou[0].key); }}>✋ {needsYou.length} {needsYou.length === 1 ? 'needs you' : 'need you'}<ChevronRight size={13}/></button>}</div>
      <div className="world-connection"><span className={`mode-indicator ${mode}`}><i/>{mode === 'demo' ? 'DEMO WORLD' : connection.toUpperCase()}</span><button className="hud-button connect" onClick={() => setConnectOpen(true)}><Plug size={16}/><span>Connect agents</span></button></div>
    </header>
    <div className="world-events" aria-live="off">{office.events.slice(0,2).map((e,i)=><div key={e.id} className={`world-event ${i ? 'older' : ''}`}><span className="event-mood">{stateMeta[e.state].emoji}</span><p><strong>{e.name}</strong> {e.activity.toLowerCase()}</p><time>{elapsed(e.at,now)}</time></div>)}</div>
    <nav className="room-rail" aria-label="Project rooms"><button className={!focus ? 'active' : ''} onClick={()=>focusRoom(null)} title="Whole office"><Home size={18}/><span>Whole office</span></button>{projects.map((p,i)=><button key={p.id} className={focus===p.id?'active':''} onClick={()=>focusRoom(p.id)} style={{'--room-color':colors[p.theme]} as React.CSSProperties} title={p.name}><span className="room-number">{String(i+1).padStart(2,'0')}</span><span>{p.name}<small>{sessionsOf(p).length} {sessionsOf(p).length===1?'session':'sessions'} · {p.agents.length} agents</small><em style={{color:teamMeta[summarizeAgents(p.agents,now).status].color}}>{teamMeta[summarizeAgents(p.agents,now).status].label}</em></span></button>)}</nav>
    {mode === 'live' && !office.agents.length && <div className="empty-office glass"><span>🪴</span><h2>Your office is open.</h2><p>Your first coworker will arrive when a connected agent sends an event.</p><button className="primary" onClick={()=>setConnectOpen(true)}>Set up the connection <Plug size={15}/></button></div>}
    {follow && selected && <div className="following-label glass"><Crosshair size={13}/> Following {selected.name}<button onClick={()=>setFollow(null)} aria-label="Stop following"><X size={13}/></button></div>}
    <div className="floor-map glass"><div><span>FLOOR PLAN</span><button aria-label="Fit office" onClick={()=>camera('home')}><Maximize2 size={12}/></button></div><Minimap projects={projects} designs={designs} focus={focus} selected={selectedKey} onFocus={focusRoom}/><p>{projects.length} projects · {office.agents.length} coworkers</p></div>
    <div className="camera-tools glass"><button title="Zoom in" aria-label="Zoom in" onClick={()=>camera('in')}><Plus size={18}/></button><button title="Zoom out" aria-label="Zoom out" onClick={()=>camera('out')}><Minus size={18}/></button><span/><button title="Rotate office" aria-label="Rotate office" onClick={()=>camera('rotate')}><RotateCw size={16}/></button><button title="Fit office · F" aria-label="Fit entire office" onClick={()=>camera('home')}><Maximize2 size={16}/></button></div>
    <footer className="game-dock glass"><div className="time-control"><button className={paused?'active':''} onClick={()=>setPaused(v=>!v)} aria-label={paused?'Resume simulation':'Pause simulation'} title="Play / pause · Space">{paused?<Play size={19} fill="currentColor"/>:<Pause size={18} fill="currentColor"/>}</button><button onClick={()=>setSpeed(1)} className={speed===1?'active':''} aria-label="Normal animation speed">1×</button><button onClick={()=>setSpeed(2)} className={speed===2?'active':''} aria-label="Double animation speed">2×</button></div><span className="dock-divider"/><button className={!panel?'active':''} onClick={()=>setPanel(null)}><Home size={18}/><span>Office</span></button><button className={panel==='team'?'active':''} onClick={()=>setPanel(v=>v==='team'?null:'team')}><Users size={18}/><span>Coworkers</span></button><button className={panel==='activity'?'active':''} onClick={()=>setPanel(v=>v==='activity'?null:'activity')}><Activity size={18}/><span>Activity</span></button><span className="dock-divider"/><button className="weather-button" onClick={()=>setEvening(v=>!v)} aria-label={evening?'Switch to daylight':'Switch to evening'}>{evening?<Moon size={19}/>:<Sun size={19}/>}<span>{evening?'After hours':'Golden hour'}</span></button><button className={panel==='settings'?'active':''} title="Office settings" aria-label="Office settings" onClick={()=>setPanel(v=>v==='settings'?null:'settings')}><Settings2 size={18}/></button></footer>
    <button className="decorate-button" onClick={()=>setLibraryOpen(true)}><span>🧱</span><div>Make it yours<small>50 worlds · 1,000 voxel props</small></div><ChevronRight size={17}/></button><div className="campus-perks glass"><span>OFFICE PERKS</span><div><button onClick={()=>worldAction('coffee')} title="Brew coffee">☕</button><button onClick={()=>worldAction('arcade')} title="Play arcade">🕹️</button><button onClick={()=>worldAction('fountain')} title="Make a wish">⛲</button><button onClick={()=>setSound(v=>!v)} aria-label={sound?'Mute sound':'Enable sound'} title={sound?'Mute sound':'Enable sound'}>{sound?'🔊':'🔇'}</button></div><small>A little break goes a long way.</small></div>{worldToast&&now-worldToast.at<3500&&<div className="world-toast" role="status" key={worldToast.at}>{worldToast.text}</div>}<div className="game-hint">Drag to orbit <span>·</span> Right-drag to pan <span>·</span> Scroll to zoom</div>
    {selected && !panel && <section className="agent-inspector glass" aria-label="Selected coworker"><button className="inspector-close" onClick={()=>{setSelectedKey('');setFollow(null)}} aria-label="Close coworker"><X size={16}/></button><div className="agent-heading"><div className={`portrait ${selected.provider}`}>{selected.name[0]}<small>{selected.provider==='codex'?'⌘':'✳'}</small></div><div><h2>{selected.name}<span>{children.length?'★':''}</span></h2><p>{children.length?'Team lead':selected.parentAgentId?'Subagent':'Agent'} · {selected.provider==='codex'?'Codex':'Claude Code'}</p>{status}</div></div><div className="inspector-project"><i style={{background:colors[selected.project.theme]}}/>{selected.project.name}<span>{elapsed(selected.at,now)} ago</span></div><div className="work-bubble"><span>{stateMeta[selectedState].emoji}</span><div><strong>{selected.task || selected.activity}</strong><p>{selectedState==='offline' && selected.state!=='offline'?'No recent signal · ':''}{selected.activity}</p></div></div><div className="agent-feeling">“{stateMeta[selectedState].feeling}”</div>{(parent || children.length>0)&&<div className="crew"><span>{parent?'REPORTS TO':'THE TEAM'}</span>{(parent?[parent]:children).map(a=><button key={a.key} onClick={()=>selectAgent(a)}><i style={{background:stateMeta[effectiveState(a,now)].color}}/>{a.name}<ChevronRight size={10}/></button>)}</div>}<div className="agent-actions"><button className={`follow-button ${follow===selected.key?'active':''}`} onClick={()=>setFollow(f=>f===selected.key?null:selected.key)}><Crosshair size={15}/>{follow===selected.key?'Following':'Follow'}</button><button onClick={()=>react('poke')} title="Poke" aria-label="Poke"><Hand size={20}/></button><button onClick={()=>react('snack')} title="Give a snack" aria-label="Give a snack"><Cookie size={21}/></button><button onClick={()=>react('cheer')} title="Cheer" aria-label="Cheer"><Heart size={20}/></button></div><p className="reaction-status" aria-live="polite">{reaction?.key===selected.key && now-reaction.at<3500?reaction.kind==='snack'?'🍪 Snack acquired. Morale: excellent.':reaction.kind==='poke'?'👀 Oh, hey! Didn’t see you there.':'💛 Thanks, human. We got this.':'Little interactions. No interruption to their work.'}</p></section>}
    {panel && <section className={`game-panel glass ${panel}`} aria-label={panel==='team'?'Coworkers':panel==='activity'?'Office activity':'Office settings'}><div className="panel-heading"><div><small>{panel==='settings'?'MAKE IT YOURS':'AROUND THE OFFICE'}</small><h2>{panel==='team'?'The coworkers':panel==='activity'?'What’s happening':'Office settings'}</h2></div><button onClick={()=>setPanel(null)} aria-label="Close panel"><X size={18}/></button></div>{panel==='team'?<><label className="search"><Search size={15}/><input aria-label="Find a coworker" placeholder="Find a coworker…" value={query} onChange={e=>setQuery(e.target.value)}/></label><TeamHierarchy projects={projects} query={query} now={now} onFocus={focusRoom} onSelect={a=>{selectAgent(a);setFollow(a.key)}}/></>:panel==='activity'?<div className="activity-list">{office.events.map(e=><div key={e.id}><span>{stateMeta[e.state].emoji}</span><p><strong>{e.name}</strong> {e.activity.toLowerCase()}<small>{e.project.name} · {e.provider==='codex'?'Codex':'Claude Code'}</small></p><time>{elapsed(e.at,now)}</time></div>)}</div>:<div className="settings-list"><button onClick={()=>setReducedMotion(v=>!v)} aria-pressed={reducedMotion}><Leaf size={18}/><span>Reduced motion<small>Keep the office calm</small></span><b>{reducedMotion?'On':'Off'}</b></button><button onClick={()=>setEvening(v=>!v)}><Moon size={18}/><span>After hours<small>Warm lights, quiet nights</small></span><b>{evening?'On':'Off'}</b></button><button onClick={()=>setConnectOpen(true)}><Plug size={18}/><span>Connect coding agents<small>Codex + Claude Code</small></span><ArrowUpRight size={15}/></button>{mode==='live'?<button onClick={()=>{enterDemo();setPanel(null);setSelectedKey('');setFollow(null);setFocus(null)}}><Home size={18}/><span>Visit the demo office</span><ArrowUpRight size={15}/></button>:officeId?<button onClick={()=>{enterLive(officeId);setPanel(null);setSelectedKey('');setFollow(null);setFocus(null)}}><Home size={18}/><span>Go to my live office</span><ArrowUpRight size={15}/></button>:null}<p>{mode==='demo'?'This office uses simulated sample activity. Connect your agents to see real work.':'Agent state comes from observed hooks. Silence is shown as an unconfirmed status.'}</p></div>}</section>}
    {libraryOpen && <Suspense fallback={<div className="world-toast">Unpacking the voxel kit…</div>}><PropLibrary projects={projects} designs={designs} onDesign={designRoom} onClose={()=>setLibraryOpen(false)} initialProject={focus} reducedMotion={reducedMotion}/></Suspense>}
    {connectOpen && <ConnectDialog onClose={()=>setConnectOpen(false)} onConnect={id=>{enterLive(id);setSelectedKey('');setFocus(null);setFollow(null)}} onDeleted={id=>{if(id===officeId)forgetOffice();setSelectedKey('');setFocus(null);setFollow(null)}}/>}
  </main>;
}
