import { Suspense,useEffect,useRef,useState } from 'react';
import { Canvas } from '@react-three/fiber';
import { Bounds,OrbitControls } from '@react-three/drei';
import { Download,Package,Plus,Search,X,Check } from 'lucide-react';
import { allProps,verticals,verticalById,propById,suggestedVertical } from '../shared/verticals.mjs';
import { VoxelModel } from './scene/VoxelModel';
import type { Designs,RoomDesign } from './scene/OfficeScene';
import type { Project } from '../shared/protocol';

export default function PropLibrary({projects,designs,onDesign,onClose,initialProject,reducedMotion}:{projects:Project[];designs:Designs;onDesign:(project:string,design:RoomDesign)=>void;onClose:()=>void;initialProject:string|null;reducedMotion:boolean}){
  const modal=useRef<HTMLElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement;modal.current?.querySelector<HTMLButtonElement>('button')?.focus();const trap=(event:KeyboardEvent)=>{if(event.key!=='Tab')return;const nodes=[...modal.current!.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select')],first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus();};},[]);
  const [projectId,setProjectId]=useState(initialProject??projects[0]?.id??''),[verticalId,setVerticalId]=useState(designs[projectId]?.vertical??suggestedVertical(projects.find(p=>p.id===projectId)?.name??'')),[query,setQuery]=useState('');
  const vertical=verticalById.get(verticalId)!,[selectedId,setSelectedId]=useState(vertical.props[0].id),[notice,setNotice]=useState('');
  const selected=propById.get(selectedId)??vertical.props[0],active=designs[projectId]??{vertical:suggestedVertical(projects.find(p=>p.id===projectId)?.name??''),props:verticalById.get(suggestedVertical(projects.find(p=>p.id===projectId)?.name??''))!.props.slice(0,8).map(p=>p.id)};
  const results=query?allProps.filter(p=>`${p.name} ${verticalById.get(p.vertical)?.name}`.toLowerCase().includes(query.toLowerCase())):vertical.props;
  useEffect(()=>{setSelectedId(vertical.props[0].id);setNotice('');},[verticalId]);
  function changeProject(id:string){setProjectId(id);setVerticalId(designs[id]?.vertical??suggestedVertical(projects.find(p=>p.id===id)?.name??''));}
  function place(){if(!projectId)return;const exists=active.props.includes(selected.id);if(!exists&&active.props.length>=12){setNotice('This room has 12 display spots. Remove a prop to make room.');return;}onDesign(projectId,{...active,props:exists?active.props.filter(id=>id!==selected.id):[...active.props,selected.id]});setNotice(exists?`${selected.name} removed.`:`${selected.name} placed in the room.`);}
  return <div className="library-backdrop" onClick={onClose}><section ref={modal} className="prop-library" role="dialog" aria-modal="true" aria-label="Voxel prop library" onClick={e=>e.stopPropagation()}>
    <header className="library-header"><div className="library-title"><span>🧱</span><div><small>THE SIDEQUEST VOXEL KIT</small><h2>A world for every idea.</h2></div></div><button aria-label="Close prop library" className="library-close" onClick={onClose}><X size={21}/></button></header>
    <div className="library-summary"><span><b>50</b> verticals</span><span><b>1,000</b> generated props</span><span>GLB assets · shared voxel families</span><a href="/packs/sidequest-voxel-kit.zip" download>Download full kit ↓</a></div>
    <div className="library-body"><aside className="vertical-list"><span className="library-caption">CHOOSE A WORLD</span>{verticals.map(v=><button key={v.id} className={verticalId===v.id?'active':''} onClick={()=>{setVerticalId(v.id);setQuery('')}}><span>{v.icon}</span><span>{v.name}</span><small>20</small></button>)}</aside>
      <div className="library-catalog"><div className="catalog-heading"><div><h3>{vertical.icon} {vertical.name}</h3><p>Twenty little objects. A completely different atmosphere.</p></div><a href={`/packs/${vertical.id}.zip`} download className="pack-download"><Download size={15}/> Pack</a></div><label className="catalog-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search all 1,000 props…" aria-label="Search props"/><span>{results.length}</span></label>
        <div className="prop-grid">{results.slice(0,100).map(prop=><button key={prop.id} className={`prop-card ${selectedId===prop.id?'active':''}`} onClick={()=>{setSelectedId(prop.id);setNotice('')}} aria-label={`Inspect ${prop.name}`}><img src={`/model-previews/${prop.id}.svg`} loading="lazy" alt=""/><strong>{prop.name}</strong><small>{active.props.includes(prop.id)?'✓ IN YOUR ROOM':verticalById.get(prop.vertical)?.name}</small></button>)}{!results.length&&<p>No props found. Try “rocket”, “camera” or “plant”.</p>}</div>{results.length>100&&<p className="catalog-limit">Showing the first 100 matches. Refine your search to see more.</p>}
      </div>
      <aside className="prop-detail"><div className="model-preview"><Canvas orthographic camera={{position:[5,4,6],zoom:50}} dpr={[1,1.5]}><ambientLight intensity={1.5}/><directionalLight position={[-3,7,5]} intensity={2}/><Suspense fallback={null}><Bounds fit clip observe margin={1.4}><VoxelModel key={selected.id} family={selected.family} color={selected.color} variant={selected.variant}/></Bounds></Suspense><OrbitControls makeDefault autoRotate={!reducedMotion} autoRotateSpeed={1.2} enablePan={false}/></Canvas><span>DRAG TO ROTATE · SCROLL TO ZOOM</span></div><div className="prop-detail-copy"><span className="library-caption">VOXEL COLLECTIBLE</span><h3>{selected.name}</h3><p>{verticalById.get(selected.vertical)?.icon} {verticalById.get(selected.vertical)?.name}</p><a href={`/models/${selected.id}.glb`} download><Download size={14}/> Download GLB</a></div>
        <div className="room-design-controls"><label>DECORATE A PROJECT<select value={projectId} onChange={e=>changeProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="place-prop" onClick={place} disabled={!projectId}>{active.props.includes(selected.id)?<Check size={16}/>:<Plus size={16}/>} {active.props.includes(selected.id)?'Remove from room':'Place in room'}</button><button className="apply-theme" disabled={!projectId} onClick={()=>{onDesign(projectId,{vertical:verticalId,props:vertical.props.slice(0,8).map(p=>p.id)});setNotice(`${vertical.name} theme applied. Your room is ready.`)}}><Package size={16}/> Apply this room theme</button><small>{active.props.length}/12 props placed · Saved on this device</small><p className="placement-notice" role="status">{notice||'Themes set the palette, room sign and eight featured props.'}</p></div>
      </aside>
    </div>
  </section></div>;
}
